CI/versioning changes
qwertyquerty/pypresence pull request #248
Opened 2024-12-28 14:42 UTC by C0rn3j

Bump version to 4.4.0

Fix up CI using deprecated actions

Fix up Python versions in setup.py to use currently supported versions by upstream

2025-01-02 19:16 UTC, NikOverflow requested changes
please fix the linting

2025-01-02 19:18 UTC, C0rn3j commented
Should be done

2025-01-02 19:49 UTC, NikOverflow commented
i look into the rest tomorrow. The vulnerabilities shouldn't affect us.

2025-01-07 08:52 UTC, C0rn3j commented
Anything left to do here on my side?

2025-01-07 14:20 UTC, NikOverflow commented
i guess not but i can't test it at the moment because i have no time.

2025-02-08 17:34 UTC, C0rn3j commented
Any chance you could find time for this, or at least make a release with the *current* master?

I am also down to spend a bit of time to fix potential issues my changes cause, although I do not believe there should be any.

2025-03-20 10:18 UTC, C0rn3j commented
I've forked the project and added this PR - https://github.com/C0rn3j/lynxpresence - as we've had a PR hanging in Tauon since the middle of December that was waiting on tagging at least current master as a new version.

I hope a release can be made so we can eventually switch back.

2025-03-27 10:58 UTC, merged

2025-03-27 11:01 UTC, NikOverflow commented
I have not the time to review everything because i also have other stuff to do. I reviewed that now. I'm not able to add an release that must do @qwertyquerty